// File generated by FlutterFire CLI / Custom Firebase Config
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey-Web-UnionRideAppConfig',
    appId: '1:100000000000:web:unionrideappdemo',
    messagingSenderId: '100000000000',
    projectId: 'unionride-app',
    authDomain: 'unionride-app.firebaseapp.com',
    storageBucket: 'unionride-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey-Android-UnionRideAppConfig',
    appId: '1:100000000000:android:unionrideappdemo',
    messagingSenderId: '100000000000',
    projectId: 'unionride-app',
    storageBucket: 'unionride-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey-iOS-UnionRideAppConfig',
    appId: '1:100000000000:ios:unionrideappdemo',
    messagingSenderId: '100000000000',
    projectId: 'unionride-app',
    storageBucket: 'unionride-app.appspot.com',
    iosBundleId: 'com.example.unionRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey-macOS-UnionRideAppConfig',
    appId: '1:100000000000:ios:unionrideappdemo',
    messagingSenderId: '100000000000',
    projectId: 'unionride-app',
    storageBucket: 'unionride-app.appspot.com',
    iosBundleId: 'com.example.unionRide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey-Windows-UnionRideAppConfig',
    appId: '1:100000000000:web:unionrideappdemo',
    messagingSenderId: '100000000000',
    projectId: 'unionride-app',
    authDomain: 'unionride-app.firebaseapp.com',
    storageBucket: 'unionride-app.appspot.com',
  );
}
