// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8F83akpl65uObaKzaul5Q8d7e_PiJw4w',
    appId: '1:820740871713:web:799477a4b4c07a46d27560',
    messagingSenderId: '820740871713',
    projectId: 'unionride-3fbd0',
    authDomain: 'unionride-3fbd0.firebaseapp.com',
    storageBucket: 'unionride-3fbd0.firebasestorage.app',
    measurementId: 'G-8JLCFL5P3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC90aDoYqGTlCstANb96yYHOBu36D0eh78',
    appId: '1:820740871713:android:78ec7d03e0fe9060d27560',
    messagingSenderId: '820740871713',
    projectId: 'unionride-3fbd0',
    storageBucket: 'unionride-3fbd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB51PUIQepwfYBX6_w4z30jX8zBmULQGA',
    appId: '1:820740871713:ios:f008a2c3394f5b53d27560',
    messagingSenderId: '820740871713',
    projectId: 'unionride-3fbd0',
    storageBucket: 'unionride-3fbd0.firebasestorage.app',
    iosBundleId: 'com.example.unionride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB51PUIQepwfYBX6_w4z30jX8zBmULQGA',
    appId: '1:820740871713:ios:f008a2c3394f5b53d27560',
    messagingSenderId: '820740871713',
    projectId: 'unionride-3fbd0',
    storageBucket: 'unionride-3fbd0.firebasestorage.app',
    iosBundleId: 'com.example.unionride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8F83akpl65uObaKzaul5Q8d7e_PiJw4w',
    appId: '1:820740871713:web:c0cf32caeeac765cd27560',
    messagingSenderId: '820740871713',
    projectId: 'unionride-3fbd0',
    authDomain: 'unionride-3fbd0.firebaseapp.com',
    storageBucket: 'unionride-3fbd0.firebasestorage.app',
    measurementId: 'G-FG7NR0BXH4',
  );
}
